import { ScenarioDefinition } from '../types';

export const SCENARIO_CATALOG: ScenarioDefinition[] = [
  // 💰 Investment
  {
    id: 'sc-inc-sip-10k',
    type: 'increase_sip',
    category: 'investment',
    title: 'Increase SIP',
    subtitle: 'Boost monthly investments into equity & mutual funds',
    description: 'See the exponential compounding effect of augmenting your monthly systematic investment plan.',
    iconName: 'TrendingUp',
    badge: 'High Impact',
    parameters: {
      newSip: 65000,
      deltaSip: 20000,
      startAge: 32,
      durationYears: 18,
    },
    parameterDefs: [
      {
        key: 'newSip',
        label: 'New Monthly SIP Amount',
        type: 'slider',
        min: 10000,
        max: 150000,
        step: 5000,
        unit: '₹',
        defaultValue: 65000,
        description: 'Your target total monthly SIP deduction',
      },
    ],
  },
  {
    id: 'sc-dec-sip',
    type: 'decrease_sip',
    category: 'investment',
    title: 'Decrease SIP',
    subtitle: 'Temporarily reduce monthly investment allocations',
    description: 'Explore the trade-offs on your retirement horizon if you scale back monthly savings.',
    iconName: 'TrendingDown',
    parameters: {
      newSip: 25000,
      deltaSip: -20000,
      startAge: 32,
      durationYears: 5,
    },
    parameterDefs: [
      {
        key: 'newSip',
        label: 'Reduced Monthly SIP',
        type: 'slider',
        min: 5000,
        max: 45000,
        step: 5000,
        unit: '₹',
        defaultValue: 25000,
        description: 'New monthly allocation',
      },
    ],
  },
  {
    id: 'sc-lump-sum-5l',
    type: 'lump_sum_investment',
    category: 'investment',
    title: 'Lump-Sum Investment',
    subtitle: 'Deploy ₹5L+ surplus or bonus into markets',
    description: 'Simulate injecting a one-time capital surplus into your long-term compounding engine.',
    iconName: 'Coins',
    parameters: {
      amount: 500000,
      startAge: 33,
    },
    parameterDefs: [
      {
        key: 'amount',
        label: 'Lump Sum Amount',
        type: 'slider',
        min: 100000,
        max: 5000000,
        step: 50000,
        unit: '₹',
        defaultValue: 500000,
        description: 'Total one-time capital to deploy',
      },
      {
        key: 'startAge',
        label: 'Investment Age',
        type: 'slider',
        min: 32,
        max: 55,
        step: 1,
        unit: 'yrs',
        defaultValue: 33,
        description: 'Age at which you invest this capital',
      },
    ],
  },
  {
    id: 'sc-change-allocation',
    type: 'change_allocation',
    category: 'investment',
    title: 'Change Asset Allocation',
    subtitle: 'Shift balance between Equity, Debt, Gold & Cash',
    description: 'Test shifting risk exposure (e.g. 70% Equity / 15% Debt / 10% Gold / 5% Cash) for higher growth.',
    iconName: 'PieChart',
    parameters: {
      equityPct: 70,
      debtPct: 15,
      goldPct: 10,
      cashPct: 5,
    },
    parameterDefs: [
      {
        key: 'equityPct',
        label: 'Equity Allocation (%)',
        type: 'slider',
        min: 10,
        max: 90,
        step: 5,
        unit: '%',
        defaultValue: 70,
      },
      {
        key: 'debtPct',
        label: 'Debt Allocation (%)',
        type: 'slider',
        min: 5,
        max: 70,
        step: 5,
        unit: '%',
        defaultValue: 15,
      },
    ],
  },
  {
    id: 'sc-stop-investing',
    type: 'stop_investing',
    category: 'investment',
    title: 'Pause SIP for 2 Years',
    subtitle: 'Let existing corpus compound without additions',
    description: 'Observe coast-FI dynamics when existing investments compound passively.',
    iconName: 'PauseCircle',
    parameters: {
      startAge: 34,
      durationYears: 2,
    },
    parameterDefs: [
      {
        key: 'durationYears',
        label: 'Pause Duration (Years)',
        type: 'slider',
        min: 1,
        max: 5,
        step: 1,
        unit: 'yrs',
        defaultValue: 2,
      },
    ],
  },

  // 🏠 Major Purchases
  {
    id: 'sc-buy-house-80l',
    type: 'buy_house',
    category: 'purchase',
    title: 'Buy an ₹80L House',
    subtitle: '20% down payment + 20-year home loan at 8.5%',
    description: 'Evaluate the dual impact of upfront liquid capital outflow, monthly EMI commitment, and property appreciation.',
    iconName: 'Home',
    badge: 'Popular',
    parameters: {
      houseCost: 8000000,
      downPaymentPct: 20,
      loanTenureYears: 20,
      startAge: 35,
    },
    parameterDefs: [
      {
        key: 'houseCost',
        label: 'Total Property Value',
        type: 'slider',
        min: 3000000,
        max: 25000000,
        step: 500000,
        unit: '₹',
        defaultValue: 8000000,
        description: 'Total purchase price of real estate',
      },
      {
        key: 'downPaymentPct',
        label: 'Down Payment Percentage',
        type: 'slider',
        min: 10,
        max: 50,
        step: 5,
        unit: '%',
        defaultValue: 20,
        description: 'Upfront cash funded from investments',
      },
      {
        key: 'startAge',
        label: 'Purchase Age',
        type: 'slider',
        min: 32,
        max: 50,
        step: 1,
        unit: 'yrs',
        defaultValue: 35,
      },
    ],
  },
  {
    id: 'sc-buy-car-20l',
    type: 'buy_car',
    category: 'purchase',
    title: 'Buy a ₹20L Car',
    subtitle: '5-year auto loan with down payment',
    description: 'Examine how depreciating vehicle costs and auto EMI alter your savings capacity.',
    iconName: 'Car',
    parameters: {
      carCost: 2000000,
      startAge: 34,
    },
    parameterDefs: [
      {
        key: 'carCost',
        label: 'Vehicle Price',
        type: 'slider',
        min: 600000,
        max: 6000000,
        step: 100000,
        unit: '₹',
        defaultValue: 2000000,
      },
      {
        key: 'startAge',
        label: 'Purchase Age',
        type: 'slider',
        min: 32,
        max: 50,
        step: 1,
        unit: 'yrs',
        defaultValue: 34,
      },
    ],
  },

  // 💼 Career
  {
    id: 'sc-salary-increase-20',
    type: 'salary_increase',
    category: 'career',
    title: 'Salary Increases by 20%',
    subtitle: 'Promotion, job switch, or appraisal boost',
    description: 'See the compounded leverage if income jumps significantly and fuels your SIP.',
    iconName: 'Briefcase',
    badge: 'Career Boost',
    parameters: {
      hikePct: 20,
      startAge: 33,
    },
    parameterDefs: [
      {
        key: 'hikePct',
        label: 'Salary Hike (%)',
        type: 'slider',
        min: 10,
        max: 60,
        step: 5,
        unit: '%',
        defaultValue: 20,
      },
      {
        key: 'startAge',
        label: 'Age of Hike',
        type: 'slider',
        min: 32,
        max: 45,
        step: 1,
        unit: 'yrs',
        defaultValue: 33,
      },
    ],
  },
  {
    id: 'sc-job-loss-6m',
    type: 'job_loss',
    category: 'career',
    title: 'Job Loss for 6 Months',
    subtitle: 'Temporary transition gap between careers',
    description: 'Stress-test emergency reserves and determine exact recovery time.',
    iconName: 'AlertTriangle',
    isShock: true,
    parameters: {
      months: 6,
      startAge: 34,
    },
    parameterDefs: [
      {
        key: 'months',
        label: 'Unemployment Duration (Months)',
        type: 'slider',
        min: 3,
        max: 18,
        step: 1,
        unit: 'mo',
        defaultValue: 6,
      },
    ],
  },
  {
    id: 'sc-career-break-2y',
    type: 'career_break',
    category: 'career',
    title: '2-Year Career Break / Sabbatical',
    subtitle: 'Step away for study, family, or travel',
    description: 'Understand the retirement timeline impact of living off savings for two years.',
    iconName: 'Compass',
    parameters: {
      durationYears: 2,
      startAge: 36,
    },
    parameterDefs: [
      {
        key: 'durationYears',
        label: 'Break Duration (Years)',
        type: 'slider',
        min: 1,
        max: 4,
        step: 1,
        unit: 'yrs',
        defaultValue: 2,
      },
      {
        key: 'startAge',
        label: 'Start Age',
        type: 'slider',
        min: 33,
        max: 45,
        step: 1,
        unit: 'yrs',
        defaultValue: 36,
      },
    ],
  },
  {
    id: 'sc-early-retirement-45',
    type: 'early_retirement',
    category: 'career',
    title: 'Retire at 45 instead of 50',
    subtitle: 'Fast-track full financial freedom',
    description: 'Check if current portfolio trajectory can support early safe withdrawals from 45.',
    iconName: 'Sun',
    parameters: {
      targetAge: 45,
    },
    parameterDefs: [
      {
        key: 'targetAge',
        label: 'Target Retirement Age',
        type: 'slider',
        min: 40,
        max: 55,
        step: 1,
        unit: 'yrs',
        defaultValue: 45,
      },
    ],
  },

  // ❤️ Life
  {
    id: 'sc-have-child',
    type: 'have_child',
    category: 'life',
    title: 'Have a Child',
    subtitle: '₹3L upfront hospital/nursery + ₹15K/mo ongoing child care',
    description: 'Model parental lifestyle adjustments, schooling costs, and long-term child support.',
    iconName: 'Baby',
    badge: 'Milestone',
    parameters: {
      upfrontCost: 300000,
      monthlyCost: 15000,
      startAge: 34,
    },
    parameterDefs: [
      {
        key: 'monthlyCost',
        label: 'Monthly Childcare & Education',
        type: 'slider',
        min: 5000,
        max: 50000,
        step: 2500,
        unit: '₹',
        defaultValue: 15000,
      },
      {
        key: 'upfrontCost',
        label: 'Initial Upfront Cost',
        type: 'slider',
        min: 100000,
        max: 1000000,
        step: 50000,
        unit: '₹',
        defaultValue: 300000,
      },
      {
        key: 'startAge',
        label: 'Parent Age',
        type: 'slider',
        min: 32,
        max: 42,
        step: 1,
        unit: 'yrs',
        defaultValue: 34,
      },
    ],
  },
  {
    id: 'sc-marriage',
    type: 'marriage',
    category: 'life',
    title: 'Marriage & Wedding Expenses',
    subtitle: '₹15L wedding & setup outflow',
    description: 'Measure the impact of one-time wedding celebration expenses on your compounding trajectory.',
    iconName: 'Heart',
    parameters: {
      marriageCost: 1500000,
      startAge: 33,
    },
    parameterDefs: [
      {
        key: 'marriageCost',
        label: 'Wedding & Setup Budget',
        type: 'slider',
        min: 500000,
        max: 4000000,
        step: 100000,
        unit: '₹',
        defaultValue: 1500000,
      },
    ],
  },
  {
    id: 'sc-support-parents',
    type: 'support_parents',
    category: 'life',
    title: 'Support Elderly Parents',
    subtitle: '₹20,000 / month recurring family care',
    description: 'Incorporate ongoing eldercare, medicine, and support allocations into monthly cash flows.',
    iconName: 'Users',
    parameters: {
      monthlySupport: 20000,
      startAge: 35,
      durationYears: 15,
    },
    parameterDefs: [
      {
        key: 'monthlySupport',
        label: 'Monthly Support Amount',
        type: 'slider',
        min: 5000,
        max: 50000,
        step: 2500,
        unit: '₹',
        defaultValue: 20000,
      },
    ],
  },
  {
    id: 'sc-relocation',
    type: 'relocation',
    category: 'life',
    title: 'Move to a Cheaper Tier-2 City',
    subtitle: 'Save ₹25,000 / month on rent & living expenses',
    description: 'Quantify geographic arbitrage and remote work cost savings over decades.',
    iconName: 'MapPin',
    parameters: {
      monthlySavings: 25000,
      startAge: 33,
      durationYears: 20,
    },
    parameterDefs: [
      {
        key: 'monthlySavings',
        label: 'Monthly Expense Savings',
        type: 'slider',
        min: 10000,
        max: 60000,
        step: 5000,
        unit: '₹',
        defaultValue: 25000,
      },
    ],
  },
  {
    id: 'sc-unexpected-windfall',
    type: 'unexpected_expense',
    category: 'life',
    title: 'Receive ₹25L Unexpected Windfall',
    subtitle: 'Inheritance, ESOP liquidity, or gift',
    description: 'Model immediate reinvestment of a large one-time windfall into long-term compounding.',
    iconName: 'Gift',
    parameters: {
      amount: 2500000,
      isWindfall: 1,
      startAge: 35,
    },
    parameterDefs: [
      {
        key: 'amount',
        label: 'Windfall Amount',
        type: 'slider',
        min: 500000,
        max: 10000000,
        step: 250000,
        unit: '₹',
        defaultValue: 2500000,
      },
    ],
  },

  // 🎯 Goals
  {
    id: 'sc-reach-1cr',
    type: 'custom_cashflow',
    category: 'goal',
    title: 'Reach ₹1 Crore Milestone Fast',
    subtitle: 'Speedrun the psychological first crore',
    description: 'Optimize savings rate to cross ₹1 Cr net worth in record time.',
    iconName: 'Target',
    parameters: {
      monthlyDelta: 25000,
      startAge: 32,
      durationYears: 4,
    },
    parameterDefs: [
      {
        key: 'monthlyDelta',
        label: 'Extra Monthly Push',
        type: 'slider',
        min: 10000,
        max: 50000,
        step: 5000,
        unit: '₹',
        defaultValue: 25000,
      },
    ],
  },
];
